language: node_js
node_js:
  - '0.10'
  - '0.12'
  - '4'
  - '6'
  - '7'
  - '10'
sudo: false
env:
  global:
    - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
install:
  - npm install --global npm
  - npm install --global yarn
  - npm install
